service: ${file(package.json):name}
version: ${file(package.json):version}

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

package:
  exclude:
    - .gitignore

functions:

  create:
    handler: handlers/create.handler
    events:
      - http:
          path: /bahoth/games
          method: post
  
  update:
    handler: handlers/update.handler
    events:
      - http:
          path: /bahoth/games/{id}
          method: patch

  get:
    handler: handlers/get.handler
    events:
      - http:
          path: /bahoth/games/{id}
          method: get
