service: ${file(package.json):name}
version: ${file(package.json):version}

# User defined shortcuts
http-defaults: &http-defaults
  integration: lambda

request-defaults: &request-defaults
  passThrough: NEVER

response-defaults: &response-defaults
  headers:
    Content-Type: "application/json"

# Serverless config
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId: ${cf:${self:custom.stack}.RestApiId}
    restApiRootResourceId: ${cf:${self:custom.stack}.RootResourceId}

custom:
  stack: bahoth-${self:provider.stage}

package:
  exclude:
    - .gitignore

functions:

  create:
    handler: handlers/create.handler
    events:
      - http:
          <<: *http-defaults
          path: /games
          method: post
          request:
            <<: *request-defaults
            template:
              application/xml: '{"body-xml": "$input.body"}'
          response:
            template: $input.path('$.body')
            statusCode:
              201:
                pattern: ''
  
  update:
    handler: handlers/update.handler
    events:
      - http:
          <<: *http-defaults
          path: /games/{id}
          method: patch

  get:
    handler: handlers/get.handler
    events:
      - http:
          path: /games/{id}
          method: get
